service: crm

package:
  exclude:
    - "**/node_modules/aws-sdk/**"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-plugin-aws-alerts

custom:
  DB_PASSWORD:
    local: password
    development: ${env:DB_PASSWORD}
    staging: ${ssm:DB_PASSWORD}
    production: ${ssm:DB_PASSWORD}
  defaultRegion: us-east-1
  defaultEnvironmentGroup: dev-staging
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, env:USER}
  objectPrefix: "${self:service}-${self:custom.stage}"
  prune:
    automatic: true
    number: 10
  alerts:
    dashboards: true
    topics:
      ok: arn:aws:sns:us-east-1:177120553227:cloudwatchAlert
      alarm: arn:aws:sns:us-east-1:177120553227:cloudwatchAlert
      insufficientData: arn:aws:sns:us-east-1:177120553227:cloudwatchAlert
    definitions: # these defaults are merged with your definitions
      functionErrors:
        period: 60 # override period

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  apiGateway:
    - ${self:custom.alias.${opt:stage, self:provider.stage}}

  # you can overwrite defaults here
  #  stage: dev
  #  region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ssm:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "states:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "lambda:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ses:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

functions:
  api:
    handler: src/handler.api
    timeout: 30
    memorySize: 824
    environment:
      NODE_ENV: ${self:custom.stage}
      DB_PASSWORD: ${env:DB_PASSWORD}
    alarms: # merged with function alarms
      - functionErrors
    events:
      - http:
          path: crm/{proxy+}
          method: ANY
          cors: true

      - http:
          path: api/crm/{proxy+}
          method: ANY
          cors: true
